ALTER TABLE "users" ADD COLUMN "googleId" TEXT;
ALTER TABLE "users" ADD COLUMN "image" TEXT;
ALTER TABLE "users" ADD COLUMN "profileComplete" BOOLEAN NOT NULL DEFAULT false;

UPDATE "users" SET "profileComplete" = true;

ALTER TABLE "users" ALTER COLUMN "passwordHash" DROP NOT NULL;
ALTER TABLE "users" ALTER COLUMN "age" DROP NOT NULL;
ALTER TABLE "users" ALTER COLUMN "sex" DROP NOT NULL;
ALTER TABLE "users" ALTER COLUMN "heightCm" DROP NOT NULL;
ALTER TABLE "users" ALTER COLUMN "weightKg" DROP NOT NULL;
ALTER TABLE "users" ALTER COLUMN "activityLevel" DROP NOT NULL;
ALTER TABLE "users" ALTER COLUMN "goal" DROP NOT NULL;
ALTER TABLE "users" ALTER COLUMN "bmi" DROP NOT NULL;
ALTER TABLE "users" ALTER COLUMN "bmr" DROP NOT NULL;
ALTER TABLE "users" ALTER COLUMN "tdee" DROP NOT NULL;

CREATE UNIQUE INDEX "users_googleId_key" ON "users"("googleId");
